server:
  port: 8760

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  cloud:
    gateway:
      # --- NEW CORS CONFIGURATION ---
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      # ------------------------------

      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2
            - AuthFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=2
            - AuthFilter

        - id: fleet-service
          uri: lb://FLEET-SERVICE
          predicates:
            - Path=/api/v1/fleet/**
          filters:
            - StripPrefix=2
            - AuthFilter

        - id: schedule-service
          uri: lb://SCHEDULE-SERVICE
          predicates:
            - Path=/api/v1/schedule/**
          filters:
            - StripPrefix=2
            - AuthFilter

        - id: schedule-service
          uri: lb://TRIP-SERVICE
          predicates:
            - Path=/api/v1/trip/**
          filters:
            - StripPrefix=2
            - AuthFilter

        - id: tracking-service
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/api/v1/tracking/**
          filters:
            - StripPrefix=2
            - AuthFilter
            # NEW: Tells the Gateway to clean up duplicated CORS headers from the downstream service
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=2
            - AuthFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

app:
  security:
    internal-secret: yK8!pL3@xQ7#dT9$wF2^sR5&vM1*bN6(

jwt:
  public-key:
    path: classpath:certs/public_key.pem